// S&P 100 (OEX) as of early 2025 — hardcoded, update quarterly
export const SP100: { symbol: string; name: string; sector: string }[] = [
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "Healthcare" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
  { symbol: "ACN", name: "Accenture plc", sector: "Technology" },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Technology" },
  { symbol: "AIG", name: "American International Group", sector: "Financials" },
  { symbol: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
  { symbol: "AMT", name: "American Tower Corp", sector: "Real Estate" },
  { symbol: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary" },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
  { symbol: "AXP", name: "American Express Co.", sector: "Financials" },
  { symbol: "BA", name: "Boeing Co.", sector: "Industrials" },
  { symbol: "BAC", name: "Bank of America Corp", sector: "Financials" },
  { symbol: "BK", name: "Bank of New York Mellon", sector: "Financials" },
  { symbol: "BKNG", name: "Booking Holdings Inc.", sector: "Consumer Discretionary" },
  { symbol: "BLK", name: "BlackRock Inc.", sector: "Financials" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare" },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc.", sector: "Financials" },
  { symbol: "C", name: "Citigroup Inc.", sector: "Financials" },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Industrials" },
  { symbol: "CHTR", name: "Charter Communications", sector: "Communication Services" },
  { symbol: "CL", name: "Colgate-Palmolive Co.", sector: "Consumer Staples" },
  { symbol: "CMCSA", name: "Comcast Corp", sector: "Communication Services" },
  { symbol: "COF", name: "Capital One Financial", sector: "Financials" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy" },
  { symbol: "COST", name: "Costco Wholesale Corp", sector: "Consumer Staples" },
  { symbol: "CRM", name: "Salesforce Inc.", sector: "Technology" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", sector: "Technology" },
  { symbol: "CVS", name: "CVS Health Corp", sector: "Healthcare" },
  { symbol: "CVX", name: "Chevron Corp", sector: "Energy" },
  { symbol: "DE", name: "Deere & Company", sector: "Industrials" },
  { symbol: "DHR", name: "Danaher Corp", sector: "Healthcare" },
  { symbol: "DIS", name: "Walt Disney Co.", sector: "Communication Services" },
  { symbol: "DOW", name: "Dow Inc.", sector: "Materials" },
  { symbol: "DUK", name: "Duke Energy Corp", sector: "Utilities" },
  { symbol: "EMR", name: "Emerson Electric Co.", sector: "Industrials" },
  { symbol: "EXC", name: "Exelon Corp", sector: "Utilities" },
  { symbol: "F", name: "Ford Motor Co.", sector: "Consumer Discretionary" },
  { symbol: "FDX", name: "FedEx Corp", sector: "Industrials" },
  { symbol: "GD", name: "General Dynamics Corp", sector: "Industrials" },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrials" },
  { symbol: "GILD", name: "Gilead Sciences Inc.", sector: "Healthcare" },
  { symbol: "GM", name: "General Motors Co.", sector: "Consumer Discretionary" },
  { symbol: "GOOG", name: "Alphabet Inc. Class C", sector: "Communication Services" },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A", sector: "Communication Services" },
  { symbol: "GS", name: "Goldman Sachs Group", sector: "Financials" },
  { symbol: "HD", name: "Home Depot Inc.", sector: "Consumer Discretionary" },
  { symbol: "HON", name: "Honeywell International", sector: "Industrials" },
  { symbol: "IBM", name: "International Business Machines", sector: "Technology" },
  { symbol: "INTC", name: "Intel Corp", sector: "Technology" },
  { symbol: "INTU", name: "Intuit Inc.", sector: "Technology" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", sector: "Financials" },
  { symbol: "KHC", name: "Kraft Heinz Co.", sector: "Consumer Staples" },
  { symbol: "KO", name: "Coca-Cola Co.", sector: "Consumer Staples" },
  { symbol: "LIN", name: "Linde plc", sector: "Materials" },
  { symbol: "LLY", name: "Eli Lilly and Co.", sector: "Healthcare" },
  { symbol: "LMT", name: "Lockheed Martin Corp", sector: "Industrials" },
  { symbol: "LOW", name: "Lowe's Companies Inc.", sector: "Consumer Discretionary" },
  { symbol: "MA", name: "Mastercard Inc.", sector: "Financials" },
  { symbol: "MCD", name: "McDonald's Corp", sector: "Consumer Discretionary" },
  { symbol: "MDLZ", name: "Mondelez International", sector: "Consumer Staples" },
  { symbol: "MDT", name: "Medtronic plc", sector: "Healthcare" },
  { symbol: "MET", name: "MetLife Inc.", sector: "Financials" },
  { symbol: "META", name: "Meta Platforms Inc.", sector: "Communication Services" },
  { symbol: "MMM", name: "3M Company", sector: "Industrials" },
  { symbol: "MO", name: "Altria Group Inc.", sector: "Consumer Staples" },
  { symbol: "MRK", name: "Merck & Co. Inc.", sector: "Healthcare" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials" },
  { symbol: "MSFT", name: "Microsoft Corp", sector: "Technology" },
  { symbol: "NEE", name: "NextEra Energy Inc.", sector: "Utilities" },
  { symbol: "NFLX", name: "Netflix Inc.", sector: "Communication Services" },
  { symbol: "NKE", name: "Nike Inc.", sector: "Consumer Discretionary" },
  { symbol: "NVDA", name: "NVIDIA Corp", sector: "Technology" },
  { symbol: "ORCL", name: "Oracle Corp", sector: "Technology" },
  { symbol: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples" },
  { symbol: "PFE", name: "Pfizer Inc.", sector: "Healthcare" },
  { symbol: "PG", name: "Procter & Gamble Co.", sector: "Consumer Staples" },
  { symbol: "PM", name: "Philip Morris International", sector: "Consumer Staples" },
  { symbol: "PYPL", name: "PayPal Holdings Inc.", sector: "Financials" },
  { symbol: "QCOM", name: "Qualcomm Inc.", sector: "Technology" },
  { symbol: "RTX", name: "RTX Corp", sector: "Industrials" },
  { symbol: "SBUX", name: "Starbucks Corp", sector: "Consumer Discretionary" },
  { symbol: "SCHW", name: "Charles Schwab Corp", sector: "Financials" },
  { symbol: "SO", name: "Southern Company", sector: "Utilities" },
  { symbol: "SPG", name: "Simon Property Group", sector: "Real Estate" },
  { symbol: "T", name: "AT&T Inc.", sector: "Communication Services" },
  { symbol: "TGT", name: "Target Corp", sector: "Consumer Discretionary" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare" },
  { symbol: "TMUS", name: "T-Mobile US Inc.", sector: "Communication Services" },
  { symbol: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary" },
  { symbol: "TXN", name: "Texas Instruments Inc.", sector: "Technology" },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", sector: "Healthcare" },
  { symbol: "UNP", name: "Union Pacific Corp", sector: "Industrials" },
  { symbol: "UPS", name: "United Parcel Service", sector: "Industrials" },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Financials" },
  { symbol: "V", name: "Visa Inc.", sector: "Financials" },
  { symbol: "VZ", name: "Verizon Communications", sector: "Communication Services" },
  { symbol: "WFC", name: "Wells Fargo & Co.", sector: "Financials" },
  { symbol: "WMT", name: "Walmart Inc.", sector: "Consumer Staples" },
  { symbol: "XOM", name: "Exxon Mobil Corp", sector: "Energy" },
];
